// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { TFHE, externalEuint64 }   from "fhevm/lib/TFHE.sol";
import { SepoliaZamaFHEVMConfig } from "fhevm/config/ZamaFHEVMConfig.sol";
import { Ownable }                from "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ConfidentialToken — ERC-7984 Confidential Token
 * @notice A fungible token where balances are fully encrypted on-chain.
 *         Implements the ERC-7984 standard for confidential tokens on FHEVM.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract ConfidentialToken is SepoliaZamaFHEVMConfig, Ownable {

    // ─── State ───────────────────────────────────────────────────────────────

    string public name;
    string public symbol;
    uint8  public decimals;
    uint64 public totalSupply;

    mapping(address => euint64) private _balances;
    mapping(address => mapping(address => euint64)) private _allowances;

    // ─── Events ──────────────────────────────────────────────────────────────

    event Transfer(address indexed from, address indexed to);
    event Approval(address indexed owner, address indexed spender);
    event Mint(address indexed to, uint64 amount);
    event Burn(address indexed from, uint64 amount);

    // ─── Constructor ─────────────────────────────────────────────────────────

    constructor(
        string memory _name,
        string memory _symbol,
        uint8         _decimals,
        uint64        initialSupply
    ) Ownable(msg.sender) {
        name     = _name;
        symbol   = _symbol;
        decimals = _decimals;

        // Mint initial supply to deployer
        _mint(msg.sender, initialSupply);
    }

    // ─── ERC-7984 Core ───────────────────────────────────────────────────────

    /// @notice Transfer encrypted amount to recipient
    function transfer(
        address         to,
        externalEuint64 encryptedAmount,
        bytes calldata  inputProof
    ) external returns (bool) {
        euint64 amount = TFHE.fromExternal(encryptedAmount, inputProof);
        TFHE.allowThis(amount);
        _transfer(msg.sender, to, amount);
        return true;
    }

    /// @notice Approve spender to transfer encrypted allowance
    function approve(
        address        spender,
        externalEuint64 encryptedAmount,
        bytes calldata inputProof
    ) external returns (bool) {
        euint64 amount = TFHE.fromExternal(encryptedAmount, inputProof);
        TFHE.allowThis(amount);
        TFHE.allow(amount, spender);
        _allowances[msg.sender][spender] = amount;
        emit Approval(msg.sender, spender);
        return true;
    }

    /// @notice Transfer from spender's allowance
    function transferFrom(
        address        from,
        address        to,
        externalEuint64 encryptedAmount,
        bytes calldata inputProof
    ) external returns (bool) {
        euint64 amount  = TFHE.fromExternal(encryptedAmount, inputProof);
        TFHE.allowThis(amount);
        euint64 allowed = _allowances[from][msg.sender];
        ebool   ok      = TFHE.le(amount, allowed);
        euint64 newAllowance = TFHE.select(ok, TFHE.sub(allowed, amount), allowed);
        TFHE.allowThis(newAllowance);
        TFHE.allow(newAllowance, msg.sender);
        _allowances[from][msg.sender] = newAllowance;
        _transfer(from, to, TFHE.select(ok, amount, TFHE.asEuint64(0)));
        return true;
    }

    // ─── Getters ─────────────────────────────────────────────────────────────

    /// @notice Returns the encrypted balance handle for an account
    function balanceOf(address account) external view returns (uint256) {
        return euint64.unwrap(_balances[account]);
    }

    /// @notice Returns the encrypted allowance handle
    function allowance(address owner, address spender) external view returns (uint256) {
        return euint64.unwrap(_allowances[owner][spender]);
    }

    // ─── Admin ───────────────────────────────────────────────────────────────

    function mint(address to, uint64 amount) external onlyOwner {
        _mint(to, amount);
        emit Mint(to, amount);
    }

    // ─── Internal ────────────────────────────────────────────────────────────

    function _transfer(address from, address to, euint64 amount) internal {
        euint64 fromBalance = _balances[from];
        euint64 newFrom     = TFHE.sub(fromBalance, amount);
        euint64 newTo       = TFHE.add(_balances[to], amount);

        TFHE.allowThis(newFrom);
        TFHE.allow(newFrom, from);
        TFHE.allowThis(newTo);
        TFHE.allow(newTo, to);

        _balances[from] = newFrom;
        _balances[to]   = newTo;

        emit Transfer(from, to);
    }

    function _mint(address to, uint64 amount) internal {
        euint64 current = _balances[to];
        euint64 minted  = TFHE.add(current, TFHE.asEuint64(amount));
        TFHE.allowThis(minted);
        TFHE.allow(minted, to);
        _balances[to] = minted;
        totalSupply  += amount;
    }
}
