// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { TFHE }                   from "fhevm/lib/TFHE.sol";
import { SepoliaZamaFHEVMConfig } from "fhevm/config/ZamaFHEVMConfig.sol";

/**
 * @title Counter — Minimal FHEVM Example
 * @notice A confidential counter where the value is encrypted on-chain.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract Counter is SepoliaZamaFHEVMConfig {
    euint64 private _count;

    constructor() {
        _count = TFHE.asEuint64(0);
        TFHE.allowThis(_count); // contract can use this handle in future txs
    }

    /// @notice Add an encrypted value to the counter
    function add(einput encryptedAmount, bytes calldata inputProof) external {
        euint64 amount = TFHE.asEuint64(encryptedAmount, inputProof);
        TFHE.allowThis(amount);
        _count = TFHE.add(_count, amount);
        TFHE.allowThis(_count);          // required after every assignment
        TFHE.allow(_count, msg.sender);  // sender can reencrypt and read
    }

    /// @notice Returns the encrypted handle — use fhevmjs.reencrypt() to read
    function getHandle() external view returns (uint256) {
        return euint64.unwrap(_count);
    }
}
