// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { TFHE, externalEuint64 } from "fhevm/lib/TFHE.sol";
import { SepoliaZamaFHEVMConfig } from "fhevm/config/ZamaFHEVMConfig.sol";

/**
 * @title Counter — Minimal FHEVM Example
 * @notice Encrypted counter: the stored value is never exposed in plaintext on-chain.
 *         Mirrors the familiar setNumber / increment interface, encrypted with TFHE.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract Counter is SepoliaZamaFHEVMConfig {
    euint64 private _number;

    constructor() {
        _number = TFHE.asEuint64(0);
        TFHE.allowThis(_number);
    }

    /// @notice Set the counter to an encrypted value.
    ///         Caller must supply a ciphertext + ZK input proof from fhevmjs.
    function setNumber(externalEuint64 encryptedNumber, bytes calldata inputProof) external {
        euint64 newNumber = TFHE.fromExternal(encryptedNumber, inputProof);
        TFHE.allowThis(newNumber);
        _number = newNumber;
        TFHE.allowThis(_number);
        TFHE.allow(_number, msg.sender);
    }

    /// @notice Increment the counter by 1. No proof needed — 1 is a public constant.
    function increment() external {
        _number = TFHE.add(_number, TFHE.asEuint64(1));
        TFHE.allowThis(_number);
    }

    /// @notice Returns the encrypted handle. Call fhevmjs.reencrypt() off-chain to read the value.
    function getHandle() external view returns (uint256) {
        return euint64.unwrap(_number);
    }
}
