// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { TFHE }                     from "fhevm/lib/TFHE.sol";
import { GatewayInterface }         from "fhevm/gateway/GatewayInterface.sol";
import { SepoliaZamaFHEVMConfig }   from "fhevm/config/ZamaFHEVMConfig.sol";
import { SepoliaZamaGatewayConfig } from "fhevm/config/ZamaGatewayConfig.sol";
import { GatewayCallbackReceiver }  from "fhevm/gateway/GatewayCallbackReceiver.sol";
import { Ownable }                  from "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title BlindAuction — Encrypted Dutch Auction on Zama FHEVM
 * @notice Bidders submit encrypted bids. No bid is ever revealed until settlement.
 *         The winning bid is determined using FHE comparison operations.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract BlindAuction is
    SepoliaZamaFHEVMConfig,
    SepoliaZamaGatewayConfig,
    GatewayCallbackReceiver,
    Ownable
{

    // ─── State ───────────────────────────────────────────────────────────────

    struct Auction {
        address  seller;
        uint64   startPrice;       // Public starting price (descending Dutch auction)
        uint64   reservePrice;     // Minimum acceptable price (public)
        uint256  endTime;
        bool     settled;
        address  winner;
        euint64  highestBid;       // Encrypted highest bid — never revealed until win
        address  highestBidder;    // Address tracking only (not amount)
    }

    struct Bid {
        euint64 amount;            // Encrypted bid amount
        bool    active;
    }

    uint256 public auctionCount;
    mapping(uint256 => Auction)              public auctions;
    mapping(uint256 => mapping(address => Bid)) private _bids;

    // Gateway decryption tracking
    mapping(uint256 => uint256) private _pendingSettlement; // requestId => auctionId
    mapping(uint256 => address) private _pendingBidder;     // requestId => bidder
    mapping(uint256 => mapping(address => euint64)) private _pendingBidHandles;

    // ─── Events ──────────────────────────────────────────────────────────────

    event AuctionCreated(uint256 indexed auctionId, address indexed seller, uint64 startPrice);
    event BidSubmitted(uint256 indexed auctionId, address indexed bidder);
    event AuctionSettled(uint256 indexed auctionId, address indexed winner);
    event SettlementRequested(uint256 indexed auctionId, uint256 requestId);

    // ─── Constructor ─────────────────────────────────────────────────────────

    constructor() Ownable(msg.sender) {}

    // ─── Auction Creation ─────────────────────────────────────────────────────

    function createAuction(
        uint64  startPrice,
        uint64  reservePrice,
        uint256 duration
    ) external returns (uint256 auctionId) {
        require(startPrice >= reservePrice, "Start price below reserve");
        require(duration > 0, "Invalid duration");

        auctionId = ++auctionCount;
        auctions[auctionId] = Auction({
            seller:        msg.sender,
            startPrice:    startPrice,
            reservePrice:  reservePrice,
            endTime:       block.timestamp + duration,
            settled:       false,
            winner:        address(0),
            highestBid:    TFHE.asEuint64(0),
            highestBidder: address(0)
        });

        TFHE.allowThis(auctions[auctionId].highestBid);

        emit AuctionCreated(auctionId, msg.sender, startPrice);
    }

    // ─── Bidding ─────────────────────────────────────────────────────────────

    function submitBid(
        uint256        auctionId,
        einput         encryptedBidAmount,
        bytes calldata inputProof
    ) external payable {
        Auction storage auction = auctions[auctionId];
        require(block.timestamp < auction.endTime, "Auction ended");
        require(!auction.settled, "Already settled");

        euint64 bid = TFHE.asEuint64(encryptedBidAmount, inputProof);
        TFHE.allowThis(bid);
        TFHE.allow(bid, msg.sender);

        // Encrypted comparison — determine if this bid is higher than current best
        ebool isHigher = TFHE.gt(bid, auction.highestBid);
        TFHE.allowThis(isHigher);

        // Update highest bid using select (FHE ternary — no branch leaks bid value)
        euint64 newHighest = TFHE.select(isHigher, bid, auction.highestBid);
        TFHE.allowThis(newHighest);
        auction.highestBid     = newHighest;

        // Track bidder (encrypted comparison result leaks only whether they're winning)
        _bids[auctionId][msg.sender] = Bid({ amount: bid, active: true });
        // Note: highestBidder tracking requires a separate mechanism in production
        // to avoid leaking bid ordering. Simplified here for template purposes.

        emit BidSubmitted(auctionId, msg.sender);
    }

    // ─── Settlement ──────────────────────────────────────────────────────────

    function requestSettlement(uint256 auctionId) external returns (uint256 requestId) {
        Auction storage auction = auctions[auctionId];
        require(block.timestamp >= auction.endTime, "Auction not ended");
        require(!auction.settled, "Already settled");

        uint256[] memory cts = new uint256[](1);
        cts[0] = Gateway.toUint256(auction.highestBid);

        requestId = Gateway.requestDecryption(
            cts,
            this._onSettlementDecrypted.selector,
            0,
            false
        );

        _pendingSettlement[requestId] = auctionId;
        emit SettlementRequested(auctionId, requestId);
    }

    /// @notice Gateway callback — reveals the winning bid amount
    function _onSettlementDecrypted(
        uint256 requestId,
        uint64  winningBidAmount
    ) external onlyGateway {
        uint256 auctionId = _pendingSettlement[requestId];
        Auction storage auction = auctions[auctionId];
        delete _pendingSettlement[requestId];

        if (winningBidAmount >= auction.reservePrice) {
            auction.settled = true;
            emit AuctionSettled(auctionId, auction.highestBidder);
        }
    }

    // ─── Getters ─────────────────────────────────────────────────────────────

    function getPendingBidHandle(uint256 auctionId, address bidder)
        external view
        returns (uint256)
    {
        return euint64.unwrap(_bids[auctionId][bidder].amount);
    }

    function isAuctionActive(uint256 auctionId) external view returns (bool) {
        Auction storage a = auctions[auctionId];
        return !a.settled && block.timestamp < a.endTime;
    }
}
