// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { TFHE }                   from "fhevm/lib/TFHE.sol";
import { SepoliaZamaFHEVMConfig } from "fhevm/config/ZamaFHEVMConfig.sol";

/**
 * @title ConfidentialDebt — Encrypted USDC debt token
 * @notice Tracks encrypted borrow amounts. Balances are never revealed on-chain.
 *         Only the vault can mint/burn debt tokens.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract ConfidentialDebt is SepoliaZamaFHEVMConfig {

    address public vault;

    mapping(address => euint64) private _debtBalances;
    mapping(address => euint64) private _liquidityBalances;

    event LiquidityDeposited(address indexed lender);
    event DebtMinted(address indexed borrower);
    event DebtBurned(address indexed borrower);

    modifier onlyVault() {
        require(msg.sender == vault, "Only vault");
        _;
    }

    function setVault(address _vault) external {
        require(vault == address(0), "Already set");
        vault = _vault;
    }

    /// @notice Lender deposits liquidity (encrypted USDC amount)
    function depositLiquidity(einput encryptedAmount, bytes calldata inputProof) external {
        euint64 amount  = TFHE.asEuint64(encryptedAmount, inputProof);
        TFHE.allowThis(amount);
        euint64 current = _liquidityBalances[msg.sender];
        euint64 newBal  = TFHE.add(current, amount);
        TFHE.allowThis(newBal);
        TFHE.allow(newBal, msg.sender);
        TFHE.allow(newBal, vault);
        _liquidityBalances[msg.sender] = newBal;
        emit LiquidityDeposited(msg.sender);
    }

    /// @notice Mint debt record for borrower — called by vault during borrow()
    function mintDebt(address borrower, euint64 amount) external onlyVault {
        euint64 current = _debtBalances[borrower];
        euint64 newDebt = TFHE.add(current, amount);
        TFHE.allowThis(newDebt);
        TFHE.allow(newDebt, borrower);
        TFHE.allow(newDebt, vault);
        _debtBalances[borrower] = newDebt;
        emit DebtMinted(borrower);
    }

    /// @notice Burn debt after repayment or liquidation
    function burnDebt(address borrower, euint64 amount) external onlyVault {
        euint64 current = _debtBalances[borrower];
        euint64 newDebt = TFHE.sub(current, amount);
        TFHE.allowThis(newDebt);
        TFHE.allow(newDebt, borrower);
        TFHE.allow(newDebt, vault);
        _debtBalances[borrower] = newDebt;
        emit DebtBurned(borrower);
    }

    /// @notice Returns the encrypted debt handle for a borrower
    function encryptedDebtOf(address borrower) external view returns (euint64) {
        return _debtBalances[borrower];
    }

    /// @notice Returns the encrypted liquidity balance handle for a lender
    function encryptedLiquidityOf(address lender) external view returns (uint256) {
        return euint64.unwrap(_liquidityBalances[lender]);
    }
}
