// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { TFHE }                   from "fhevm/lib/TFHE.sol";
import { SepoliaZamaFHEVMConfig } from "fhevm/config/ZamaFHEVMConfig.sol";

/**
 * @title ConfidentialCollateral — Encrypted ETH wrapper (cETH)
 * @notice Wraps ETH into a confidential token. Balances are encrypted on-chain.
 *         Only the vault can call mintDebt/burn functions.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract ConfidentialCollateral is SepoliaZamaFHEVMConfig {

    address public vault;
    mapping(address => euint64) private _balances;

    event Wrapped(address indexed account, uint256 ethAmount);

    modifier onlyVault() {
        require(msg.sender == vault, "Only vault");
        _;
    }

    function setVault(address _vault) external {
        require(vault == address(0), "Already set");
        vault = _vault;
    }

    /// @notice Wrap ETH into encrypted cETH — called by the vault during borrow()
    function wrapAndDeposit(address recipient) external payable onlyVault {
        require(msg.value > 0, "No ETH sent");

        // Convert wei to gwei (uint64 range: up to ~18.4 ETH)
        uint64 gweiAmount = uint64(msg.value / 1 gwei);
        euint64 current   = _balances[recipient];
        euint64 newBal    = TFHE.add(current, TFHE.asEuint64(gweiAmount));

        TFHE.allowThis(newBal);
        TFHE.allow(newBal, recipient);
        TFHE.allow(newBal, vault);

        _balances[recipient] = newBal;
        emit Wrapped(recipient, msg.value);
    }

    /// @notice Returns the encrypted balance handle for a user
    function encryptedBalanceOf(address account) external view returns (euint64) {
        return _balances[account];
    }

    /// @notice Burn collateral during liquidation
    function burn(address from, euint64 amount) external onlyVault {
        euint64 current = _balances[from];
        euint64 newBal  = TFHE.sub(current, amount);
        TFHE.allowThis(newBal);
        TFHE.allow(newBal, from);
        TFHE.allow(newBal, vault);
        _balances[from] = newBal;
    }
}
