// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { FHE }                 from "@fhevm/solidity/lib/FHE.sol";
import { ZamaEthereumConfig }  from "@fhevm/solidity/config/ZamaConfig.sol";
import { euint64, externalEuint64 } from "encrypted-types/EncryptedTypes.sol";

/**
 * @title ConfidentialDebt — Encrypted USDC debt token
 * @notice Tracks encrypted borrow amounts. Balances are never revealed on-chain.
 *         Only the vault can mint/burn debt tokens.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract ConfidentialDebt is ZamaEthereumConfig {

    address public vault;

    mapping(address => euint64) private _debtBalances;
    mapping(address => euint64) private _liquidityBalances;

    event LiquidityDeposited(address indexed lender);
    event DebtMinted(address indexed borrower);
    event DebtBurned(address indexed borrower);

    modifier onlyVault() {
        require(msg.sender == vault, "Only vault");
        _;
    }

    function setVault(address _vault) external {
        require(vault == address(0), "Already set");
        vault = _vault;
    }

    /// @notice Lender deposits liquidity (encrypted USDC amount)
    function depositLiquidity(externalEuint64 encryptedAmount, bytes calldata inputProof) external {
        euint64 amount  = FHE.fromExternal(encryptedAmount, inputProof);
        FHE.allowThis(amount);
        euint64 newBal  = FHE.add(_liquidityBalances[msg.sender], amount);
        FHE.allowThis(newBal);
        FHE.allow(newBal, msg.sender);
        FHE.allow(newBal, vault);
        _liquidityBalances[msg.sender] = newBal;
        emit LiquidityDeposited(msg.sender);
    }

    /// @notice Mint debt record for borrower — called by vault during borrow()
    function mintDebt(address borrower, euint64 amount) external onlyVault {
        euint64 newDebt = FHE.add(_debtBalances[borrower], amount);
        FHE.allowThis(newDebt);
        FHE.allow(newDebt, borrower);
        FHE.allow(newDebt, vault);
        _debtBalances[borrower] = newDebt;
        emit DebtMinted(borrower);
    }

    /// @notice Burn debt after repayment or liquidation
    function burnDebt(address borrower, euint64 amount) external onlyVault {
        euint64 newDebt = FHE.sub(_debtBalances[borrower], amount);
        FHE.allowThis(newDebt);
        FHE.allow(newDebt, borrower);
        FHE.allow(newDebt, vault);
        _debtBalances[borrower] = newDebt;
        emit DebtBurned(borrower);
    }

    /// @notice Returns the encrypted debt handle for a borrower
    function encryptedDebtOf(address borrower) external view returns (euint64) {
        return _debtBalances[borrower];
    }

    /// @notice Returns the encrypted liquidity balance handle for a lender
    function encryptedLiquidityOf(address lender) external view returns (bytes32) {
        return euint64.unwrap(_liquidityBalances[lender]);
    }
}
