// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { FHE }                from "@fhevm/solidity/lib/FHE.sol";
import { ZamaEthereumConfig } from "@fhevm/solidity/config/ZamaConfig.sol";
import { Ownable }            from "@openzeppelin-contracts/access/Ownable.sol";
import { euint64, ebool, externalEuint64 } from "encrypted-types/EncryptedTypes.sol";
import { ConfidentialCollateral }    from "./tokens/ConfidentialCollateral.sol";
import { ConfidentialDebt }          from "./tokens/ConfidentialDebt.sol";

/**
 * @title ConfidentialVault
 * @notice Confidential lending vault using Zama FHEVM.
 *         Collateral and debt amounts are encrypted on-chain.
 *         Health factor checks run in FHE — no ZK proofs needed.
 *
 * Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract ConfidentialVault is ZamaEthereumConfig, Ownable {

    // ─── State ───────────────────────────────────────────────────────────────

    ConfidentialCollateral public immutable collateralToken;
    ConfidentialDebt       public immutable debtToken;

    uint64 public constant LIQUIDATION_THRESHOLD = 150; // 150% collateralization
    uint64 public constant TRIGGER_FEE_BPS       = 100; // 1% fee for liquidation trigger
    uint64 public constant PROTOCOL_FEE_BPS      = 50;  // 0.5% protocol fee

    struct Position {
        euint64 collateral; // encrypted collateral (gwei units)
        euint64 debt;       // encrypted debt (6-decimal USDC units)
        bool    active;
        uint256 openedAt;
    }

    mapping(address => Position) private _positions;
    address[]                    private _positionOwners;

    // Pending health check handles awaiting public decryption
    mapping(address => ebool) private _pendingHealthHandle;     // borrower => unhealthy flag
    mapping(address => address) private _pendingRequestInitiator; // borrower => agent

    // ─── Events ──────────────────────────────────────────────────────────────

    event PositionOpened(address indexed borrower, uint256 timestamp);
    event HealthCheckRequested(address indexed borrower, bytes32 healthHandle);
    event AuctionTriggered(address indexed borrower, address indexed agent);
    event PositionClosed(address indexed borrower);

    // ─── Constructor ─────────────────────────────────────────────────────────

    constructor(address _collateral, address _debt) Ownable(msg.sender) {
        collateralToken = ConfidentialCollateral(_collateral);
        debtToken       = ConfidentialDebt(_debt);
    }

    // ─── Lender Flow ─────────────────────────────────────────────────────────

    function depositLiquidity(externalEuint64 encryptedAmount, bytes calldata inputProof) external {
        debtToken.depositLiquidity(encryptedAmount, inputProof);
    }

    // ─── Borrower Flow ───────────────────────────────────────────────────────

    function borrow(externalEuint64 encryptedBorrowAmount, bytes calldata inputProof) external payable {
        require(msg.value > 0, "No ETH collateral");
        require(!_positions[msg.sender].active, "Position exists");

        collateralToken.wrapAndDeposit{value: msg.value}(msg.sender);
        euint64 collateral = collateralToken.encryptedBalanceOf(msg.sender);
        FHE.allowThis(collateral);
        FHE.allow(collateral, msg.sender);

        euint64 debt = FHE.fromExternal(encryptedBorrowAmount, inputProof);
        FHE.allowThis(debt);
        FHE.allow(debt, msg.sender);
        FHE.allow(debt, address(debtToken));

        _positions[msg.sender] = Position({
            collateral: collateral,
            debt:       debt,
            active:     true,
            openedAt:   block.timestamp
        });
        _positionOwners.push(msg.sender);

        debtToken.mintDebt(msg.sender, debt);
        emit PositionOpened(msg.sender, block.timestamp);
    }

    // ─── Health Factor (FHE — replaces ZK circuits) ───────────────────────────

    function _computeHealthCheck(address borrower) internal returns (ebool) {
        Position storage pos = _positions[borrower];
        require(pos.active, "No active position");

        // Price is public (oracle) — used as a scalar multiplier
        uint64 ethPriceUsd = 3000_000000; // TODO: wire Chainlink oracle

        // Encrypted arithmetic — never reveals position size
        euint64 collateralUsd = FHE.mul(pos.collateral, ethPriceUsd);
        euint64 required      = FHE.mul(pos.debt, LIQUIDATION_THRESHOLD);
        euint64 scaled        = FHE.mul(collateralUsd, uint64(100));

        FHE.allowThis(collateralUsd);
        FHE.allowThis(required);
        FHE.allowThis(scaled);

        return FHE.lt(scaled, required); // true = undercollateralized
    }

    // ─── Liquidation Flow ────────────────────────────────────────────────────

    /// @notice Step 1: compute health flag and mark it for public decryption.
    ///         Off-chain keeper then calls executeHealthCheck() with the KMS proof.
    function requestHealthCheck(address borrower) external returns (ebool unhealthyHandle) {
        unhealthyHandle = _computeHealthCheck(borrower);
        FHE.allowThis(unhealthyHandle);
        FHE.makePubliclyDecryptable(unhealthyHandle);

        _pendingHealthHandle[borrower]      = unhealthyHandle;
        _pendingRequestInitiator[borrower]  = msg.sender;

        emit HealthCheckRequested(borrower, ebool.unwrap(unhealthyHandle));
    }

    /// @notice Step 2: keeper provides the KMS decryption proof; vault liquidates if unhealthy.
    function executeHealthCheck(
        address          borrower,
        bytes32[] calldata handles,
        bytes    calldata abiEncodedCleartexts,
        bytes    calldata decryptionProof
    ) external {
        FHE.checkSignatures(handles, abiEncodedCleartexts, decryptionProof);

        uint256[] memory cleartexts = abi.decode(abiEncodedCleartexts, (uint256[]));
        bool isUndercollateralized  = cleartexts[0] != 0;
        address triggeringAgent    = _pendingRequestInitiator[borrower];

        _pendingHealthHandle[borrower]     = ebool.wrap(bytes32(0));
        _pendingRequestInitiator[borrower] = address(0);

        if (!isUndercollateralized) return;

        _positions[borrower].active = false;
        emit AuctionTriggered(borrower, triggeringAgent);
    }

    // ─── Getters ─────────────────────────────────────────────────────────────

    /// @notice Returns collateral and debt handles for a position.
    function getPositionHandles(address borrower)
        external view
        returns (bytes32 collateralHandle, bytes32 debtHandle)
    {
        Position storage pos = _positions[borrower];
        return (euint64.unwrap(pos.collateral), euint64.unwrap(pos.debt));
    }

    /// @notice Returns the pending health check handle for keeper resolution.
    function getPendingHealthHandle(address borrower) external view returns (bytes32) {
        return ebool.unwrap(_pendingHealthHandle[borrower]);
    }

    /// @notice Returns true if a health check is pending for this borrower.
    function hasPendingCheck(address borrower) external view returns (bool) {
        return FHE.isInitialized(_pendingHealthHandle[borrower]);
    }

    /// @notice Returns named loan info.
    function getLoanInfo(address borrower)
        external view
        returns (bool active, uint256 openedAt)
    {
        Position storage pos = _positions[borrower];
        return (pos.active, pos.openedAt);
    }

    function getActivePositions() external view returns (address[] memory) {
        uint256 count;
        for (uint256 i; i < _positionOwners.length; ++i) {
            if (_positions[_positionOwners[i]].active) ++count;
        }
        address[] memory active = new address[](count);
        uint256 j;
        for (uint256 i; i < _positionOwners.length; ++i) {
            if (_positions[_positionOwners[i]].active) active[j++] = _positionOwners[i];
        }
        return active;
    }

    // ─── Access Control ───────────────────────────────────────────────────────

    /// @notice Grant an external agent FHE read access to a position.
    function grantAgentAccess(address borrower, address agent) external onlyOwner {
        Position storage pos = _positions[borrower];
        require(pos.active, "Position not active");
        FHE.allow(pos.collateral, agent);
        FHE.allow(pos.debt,       agent);
    }
}
