// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { TFHE }                      from "fhevm/lib/TFHE.sol";
import { GatewayInterface }          from "fhevm/gateway/GatewayInterface.sol";
import { SepoliaZamaFHEVMConfig }    from "fhevm/config/ZamaFHEVMConfig.sol";
import { SepoliaZamaGatewayConfig }  from "fhevm/config/ZamaGatewayConfig.sol";
import { GatewayCallbackReceiver }   from "fhevm/gateway/GatewayCallbackReceiver.sol";
import { Ownable }                   from "@openzeppelin/contracts/access/Ownable.sol";
import { ConfidentialCollateral }    from "./tokens/ConfidentialCollateral.sol";
import { ConfidentialDebt }          from "./tokens/ConfidentialDebt.sol";

/**
 * @title ConfidentialVault
 * @notice Confidential lending vault using Zama FHEVM.
 *         Collateral and debt amounts are encrypted on-chain.
 *         Health factor checks run in FHE — no ZK proofs needed.
 *
 * Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract ConfidentialVault is
    SepoliaZamaFHEVMConfig,
    SepoliaZamaGatewayConfig,
    GatewayCallbackReceiver,
    Ownable
{

    // ─── State ───────────────────────────────────────────────────────────────

    ConfidentialCollateral public immutable collateralToken;
    ConfidentialDebt       public immutable debtToken;

    uint64 public constant LIQUIDATION_THRESHOLD = 150; // 150% collateralization
    uint64 public constant TRIGGER_FEE_BPS       = 100; // 1% fee for liquidation trigger
    uint64 public constant PROTOCOL_FEE_BPS      = 50;  // 0.5% protocol fee

    struct Position {
        euint64 collateral; // encrypted collateral (gwei units)
        euint64 debt;       // encrypted debt (6-decimal USDC units)
        bool    active;
        uint256 openedAt;
    }

    mapping(address => Position) private _positions;
    address[]                    private _positionOwners;

    // Pending Gateway decryption requests
    mapping(uint256 => address) private _pendingHealthCheck;      // requestId => borrower
    mapping(uint256 => address) private _pendingRequestInitiator; // requestId => agent
    mapping(address => euint64) private _pendingHealthHandle;     // borrower => handle

    // ─── Events ──────────────────────────────────────────────────────────────

    event PositionOpened(address indexed borrower, uint256 timestamp);
    event HealthCheckRequested(address indexed borrower, uint256 requestId);
    event AuctionTriggered(address indexed borrower, address indexed agent);
    event PositionClosed(address indexed borrower);

    // ─── Constructor ─────────────────────────────────────────────────────────

    constructor(address _collateral, address _debt) Ownable(msg.sender) {
        collateralToken = ConfidentialCollateral(_collateral);
        debtToken       = ConfidentialDebt(_debt);
    }

    // ─── Lender Flow ─────────────────────────────────────────────────────────

    function depositLiquidity(einput encryptedAmount, bytes calldata inputProof) external {
        debtToken.depositLiquidity(encryptedAmount, inputProof);
    }

    // ─── Borrower Flow ───────────────────────────────────────────────────────

    function borrow(einput encryptedBorrowAmount, bytes calldata inputProof) external payable {
        require(msg.value > 0, "No ETH collateral");
        require(!_positions[msg.sender].active, "Position exists");

        collateralToken.wrapAndDeposit{value: msg.value}(msg.sender);
        euint64 collateral = collateralToken.encryptedBalanceOf(msg.sender);
        TFHE.allowThis(collateral);
        TFHE.allow(collateral, msg.sender);

        euint64 debt = TFHE.asEuint64(encryptedBorrowAmount, inputProof);
        TFHE.allowThis(debt);
        TFHE.allow(debt, msg.sender);

        _positions[msg.sender] = Position({
            collateral: collateral,
            debt:       debt,
            active:     true,
            openedAt:   block.timestamp
        });
        _positionOwners.push(msg.sender);

        debtToken.mintDebt(msg.sender, debt);
        emit PositionOpened(msg.sender, block.timestamp);
    }

    // ─── Health Factor (FHE — replaces ZK circuits) ───────────────────────────

    function _computeHealthCheck(address borrower) internal returns (ebool) {
        Position storage pos = _positions[borrower];
        require(pos.active, "No active position");

        // Price is public (oracle) — used as a scalar multiplier
        uint64 ethPriceUsd = 3000_000000; // TODO: wire Chainlink oracle

        // Encrypted arithmetic — never reveals position size
        euint64 collateralUsd = TFHE.mul(pos.collateral, TFHE.asEuint64(ethPriceUsd));
        euint64 required      = TFHE.mul(pos.debt, TFHE.asEuint64(LIQUIDATION_THRESHOLD));
        euint64 scaled        = TFHE.mul(collateralUsd, TFHE.asEuint64(100));

        TFHE.allowThis(collateralUsd);
        TFHE.allowThis(required);
        TFHE.allowThis(scaled);

        return TFHE.lt(scaled, required); // true = undercollateralized
    }

    // ─── Liquidation Flow ────────────────────────────────────────────────────

    function requestHealthCheck(address borrower) external returns (uint256 requestId) {
        ebool unhealthy = _computeHealthCheck(borrower);
        TFHE.allowThis(unhealthy);

        uint256[] memory cts = new uint256[](1);
        cts[0] = Gateway.toUint256(unhealthy);

        requestId = Gateway.requestDecryption(
            cts,
            this._onHealthCheckDecrypted.selector,
            0,
            false
        );

        _pendingHealthCheck[requestId]      = borrower;
        _pendingRequestInitiator[requestId] = tx.origin;

        emit HealthCheckRequested(borrower, requestId);
    }

    /// @notice Zama Gateway callback — fires ~2-5 sec after requestHealthCheck()
    /// @dev onlyGateway prevents anyone else from calling this with fake results
    function _onHealthCheckDecrypted(
        uint256 requestId,
        bool    isUndercollateralized
    ) external onlyGateway {
        address borrower        = _pendingHealthCheck[requestId];
        address triggeringAgent = _pendingRequestInitiator[requestId];
        delete _pendingHealthCheck[requestId];
        delete _pendingRequestInitiator[requestId];

        if (!isUndercollateralized) return;

        _positions[borrower].active = false;
        emit AuctionTriggered(borrower, triggeringAgent);
    }

    // ─── Getters ─────────────────────────────────────────────────────────────

    /// @notice Returns collateral and debt handles for a position.
    ///         Only 2 values. Health handle is separate — use getPendingHealthHandle().
    function getPositionHandles(address borrower)
        external view
        returns (uint256 collateralHandle, uint256 debtHandle)
    {
        Position storage pos = _positions[borrower];
        return (euint64.unwrap(pos.collateral), euint64.unwrap(pos.debt));
    }

    /// @notice Returns the pending health check handle for Relayer SDK resolution.
    function getPendingHealthHandle(address borrower) external view returns (uint256) {
        euint64 handle = _pendingHealthHandle[borrower];
        return euint64.unwrap(handle);
    }

    /// @notice Returns true if a health check is pending for this borrower.
    function hasPendingCheck(address borrower) external view returns (bool) {
        return TFHE.isInitialized(_pendingHealthHandle[borrower]);
    }

    /// @notice Returns named loan info. Status is a separate hasPendingCheck() call.
    function getLoanInfo(address borrower)
        external view
        returns (bool active, uint256 openedAt)
    {
        Position storage pos = _positions[borrower];
        return (pos.active, pos.openedAt);
    }

    function getActivePositions() external view returns (address[] memory) {
        uint256 count;
        for (uint256 i; i < _positionOwners.length; ++i) {
            if (_positions[_positionOwners[i]].active) ++count;
        }
        address[] memory active = new address[](count);
        uint256 j;
        for (uint256 i; i < _positionOwners.length; ++i) {
            if (_positions[_positionOwners[i]].active) active[j++] = _positionOwners[i];
        }
        return active;
    }

    // ─── Access Control ───────────────────────────────────────────────────────

    /// @notice Grant an external agent FHE read access to a position.
    function grantAgentAccess(address borrower, address agent) external onlyOwner {
        Position storage pos = _positions[borrower];
        require(pos.active, "Position not active");
        TFHE.allow(pos.collateral, agent);
        TFHE.allow(pos.debt,       agent);
    }
}
