// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { Ownable } from "@openzeppelin-contracts/access/Ownable.sol";

/**
 * @title PriceOracle — Simple ETH/USD price oracle stub
 * @notice Returns ETH price in USD with 6 decimals (e.g. 3000_000000 = $3000).
 *         Replace with Chainlink integration for production.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract PriceOracle is Ownable {

    uint64 private _ethUsdPrice;

    event PriceUpdated(uint64 newPrice);

    constructor(uint64 initialPrice) Ownable(msg.sender) {
        _ethUsdPrice = initialPrice;
    }

    /// @notice Returns ETH/USD price with 6 decimal places
    function getEthUsdPrice() external view returns (uint64) {
        return _ethUsdPrice;
    }

    /// @notice Update price (owner only — replace with Chainlink in production)
    function updatePrice(uint64 newPrice) external onlyOwner {
        require(newPrice > 0, "Price must be positive");
        _ethUsdPrice = newPrice;
        emit PriceUpdated(newPrice);
    }
}
