// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { TFHE }                     from "fhevm/lib/TFHE.sol";
import { GatewayInterface }         from "fhevm/gateway/GatewayInterface.sol";
import { SepoliaZamaFHEVMConfig }   from "fhevm/config/ZamaFHEVMConfig.sol";
import { SepoliaZamaGatewayConfig } from "fhevm/config/ZamaGatewayConfig.sol";
import { GatewayCallbackReceiver }  from "fhevm/gateway/GatewayCallbackReceiver.sol";
import { Ownable }                  from "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ConfidentialVoting — Encrypted Voting on Zama FHEVM
 * @notice Votes are encrypted on-chain. Individual choices are never revealed.
 *         Tallies are decrypted only after the voting period ends.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract ConfidentialVoting is
    SepoliaZamaFHEVMConfig,
    SepoliaZamaGatewayConfig,
    GatewayCallbackReceiver,
    Ownable
{

    // ─── State ───────────────────────────────────────────────────────────────

    struct Proposal {
        string  description;
        euint64 yesVotes;    // Encrypted running tally
        euint64 noVotes;
        uint256 endTime;
        bool    tallied;
        uint64  finalYes;   // Set after tally decryption
        uint64  finalNo;
    }

    uint256 public proposalCount;
    mapping(uint256 => Proposal)          public proposals;
    mapping(uint256 => mapping(address => bool)) public hasVoted;
    mapping(address => bool)              public registeredVoters;

    // Gateway tracking
    mapping(uint256 => uint256) private _pendingTally; // requestId => proposalId

    // ─── Events ──────────────────────────────────────────────────────────────

    event VoterRegistered(address indexed voter);
    event ProposalCreated(uint256 indexed proposalId, string description);
    event VoteCast(uint256 indexed proposalId, address indexed voter);
    event TallyRequested(uint256 indexed proposalId, uint256 requestId);
    event TallyComplete(uint256 indexed proposalId, uint64 yes, uint64 no);

    // ─── Constructor ─────────────────────────────────────────────────────────

    constructor() Ownable(msg.sender) {}

    // ─── Admin ───────────────────────────────────────────────────────────────

    function registerVoter(address voter) external onlyOwner {
        registeredVoters[voter] = true;
        emit VoterRegistered(voter);
    }

    function createProposal(
        string calldata description,
        uint256         duration
    ) external onlyOwner returns (uint256 proposalId) {
        require(duration > 0, "Invalid duration");

        proposalId = ++proposalCount;
        Proposal storage p = proposals[proposalId];
        p.description = description;
        p.endTime     = block.timestamp + duration;
        p.yesVotes    = TFHE.asEuint64(0);
        p.noVotes     = TFHE.asEuint64(0);

        TFHE.allowThis(p.yesVotes);
        TFHE.allowThis(p.noVotes);

        emit ProposalCreated(proposalId, description);
    }

    // ─── Voting ──────────────────────────────────────────────────────────────

    /// @notice Cast an encrypted vote: 1 = yes, 0 = no
    function castVote(
        uint256        proposalId,
        einput         encryptedVote,
        bytes calldata inputProof
    ) external {
        require(registeredVoters[msg.sender], "Not a registered voter");
        require(!hasVoted[proposalId][msg.sender], "Already voted");

        Proposal storage p = proposals[proposalId];
        require(block.timestamp < p.endTime, "Voting period ended");
        require(!p.tallied, "Already tallied");

        // Encrypt the vote — 1 = yes, 0 = no
        euint64 vote = TFHE.asEuint64(encryptedVote, inputProof);
        TFHE.allowThis(vote);

        // ebool: is this a yes vote?
        ebool isYes = TFHE.gt(vote, TFHE.asEuint64(0));
        TFHE.allowThis(isYes);

        // Add encrypted 1 to the appropriate tally using select
        euint64 one = TFHE.asEuint64(1);
        TFHE.allowThis(one);

        euint64 newYes = TFHE.add(p.yesVotes, TFHE.select(isYes, one, TFHE.asEuint64(0)));
        euint64 newNo  = TFHE.add(p.noVotes,  TFHE.select(isYes, TFHE.asEuint64(0), one));

        TFHE.allowThis(newYes);
        TFHE.allowThis(newNo);

        p.yesVotes = newYes;
        p.noVotes  = newNo;

        hasVoted[proposalId][msg.sender] = true;
        emit VoteCast(proposalId, msg.sender);
    }

    // ─── Tally ───────────────────────────────────────────────────────────────

    /// @notice Request decryption of the final vote tally
    function requestTally(uint256 proposalId) external returns (uint256 requestId) {
        Proposal storage p = proposals[proposalId];
        require(block.timestamp >= p.endTime, "Voting not ended");
        require(!p.tallied, "Already tallied");

        uint256[] memory cts = new uint256[](2);
        cts[0] = Gateway.toUint256(p.yesVotes);
        cts[1] = Gateway.toUint256(p.noVotes);

        requestId = Gateway.requestDecryption(
            cts,
            this._onTallyDecrypted.selector,
            0,
            false
        );

        _pendingTally[requestId] = proposalId;
        emit TallyRequested(proposalId, requestId);
    }

    /// @notice Gateway callback — receives decrypted tally
    function _onTallyDecrypted(
        uint256 requestId,
        uint64  yesVotes,
        uint64  noVotes
    ) external onlyGateway {
        uint256 proposalId = _pendingTally[requestId];
        Proposal storage p = proposals[proposalId];
        delete _pendingTally[requestId];

        p.tallied  = true;
        p.finalYes = yesVotes;
        p.finalNo  = noVotes;

        emit TallyComplete(proposalId, yesVotes, noVotes);
    }

    // ─── Getters ─────────────────────────────────────────────────────────────

    function getResult(uint256 proposalId)
        external view
        returns (bool tallied, uint64 yes, uint64 no, bool passed)
    {
        Proposal storage p = proposals[proposalId];
        return (p.tallied, p.finalYes, p.finalNo, p.finalYes > p.finalNo);
    }

    function isVotingActive(uint256 proposalId) external view returns (bool) {
        Proposal storage p = proposals[proposalId];
        return block.timestamp < p.endTime && !p.tallied;
    }
}
